/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Announcement: typeof import('./src/components/pages/home/announcement.vue')['default']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ClassTable: typeof import('./src/components/pages/main/classTable.vue')['default']
    Footer: typeof import('./src/components/layout/footer.vue')['default']
    Intro: typeof import('./src/components/pages/home/intro.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/loadingSpinner.vue')['default']
    Loginarea: typeof import('./src/components/pages/login/loginarea.vue')['default']
    Navbar: typeof import('./src/components/layout/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search_box: typeof import('./src/components/pages/main/search_box.vue')['default']
  }
}
