/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ClassTable: typeof import('./src/components/pages/main/classTable.vue')['default']
    ClipLoadingSpinner: typeof import('./src/components/common/ClipLoadingSpinner.vue')['default']
    ColorTemplate: typeof import('./src/components/pages/main/colorTemplate.vue')['default']
    Comment: typeof import('./src/components/pages/main/comment.vue')['default']
    CommonOption: typeof import('./src/components/common/option/commonOption.vue')['default']
    CourseCard: typeof import('./src/components/pages/main/courseCard.vue')['default']
    Footer: typeof import('./src/components/layout/footer.vue')['default']
    InputArea: typeof import('./src/components/pages/main/inputArea.vue')['default']
    Intro: typeof import('./src/components/pages/home/intro.vue')['default']
    KebabButton: typeof import('./src/components/common/optionButton/kebabButton.vue')['default']
    LoadingSpinner: typeof import('./src/components/common/loadingSpinner.vue')['default']
    Loginarea: typeof import('./src/components/pages/login/loginarea.vue')['default']
    Navbar: typeof import('./src/components/layout/navbar.vue')['default']
    Notify: typeof import('./src/components/pages/home/notify.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Search_box: typeof import('./src/components/pages/main/search_box.vue')['default']
    TimeSelection: typeof import('./src/components/pages/main/timeSelection.vue')['default']
    Tutorial: typeof import('./src/components/pages/tutorial/tutorial.vue')['default']
  }
}
