/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Announcement: typeof import('./src/components/announcement.vue')['default']
    ASpace: typeof import('ant-design-vue/es')['Space']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ClassTable: typeof import('./src/components/classTable.vue')['default']
    Footer: typeof import('./src/components/footer.vue')['default']
    Intro: typeof import('./src/components/intro.vue')['default']
    Loginarea: typeof import('./src/components/loginarea.vue')['default']
    Navbar: typeof import('./src/components/navbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
